### ISSUE TITLE
Specify arbitrary Julia project for the language server similar to `julia --project=/path/to/project`

### ISSUE THREAD

**Issue by johannesnauta** [non-Jedi/eglot-jl#38]
I am not sure if this is the right place to ask, but here goes.

### Sketch of the situtation
I have a directory structure wherein I am developing a (local) package. 
```bash
MyPkg/
├── Project.toml
└── src
    └── MyPkg.jl
```
The file I want to work in is somewhere else entirely, e.g. in a separate Julia file called `run.jl`, say in `~/code/run.jl`.
Now, normally, I'd run `julia --project=/path/to/MyPkg` and in the Julia REPL I can 
```julia
julia> using MyPkg
```
However, when loading `run.jl` in Emacs using `eglot` and `eglot-jl`, the linter shows errors related to undefined references.

### Question
Is there a way to tell `eglot` (or `eglot-jl`) to load the language server for an arbitrary project, similar to how 
`julia --project=/path/to/project` functions? Or, how can I tell `eglot` what the current Julia project should be?

**Comment by ffevotte** [comment]
The short answer is that there currently is no way to do what you ask: in the current implementation, the Julia script starting the Language Server can be given a project path, but the elisp part of `eglot-jl` currently always feeds it with the directory of the source file being edited (`run.jl` in your example).

*As a side note, I personally never run into such an issue because I tend to put scripts (like `run.jl`) in the top-level directory of the package under development (i.e. alongside its `Project.toml` file). It's always possible to also symlink the script somewhere else if needed. But maybe this would not fit your workflow...*

The longer answer is that we already have all the required building blocks; the only missing piece is the UI: we're missing a mechanism to "to what the user means" and feed the correct project path to the Language Server. Would you have an idea of an ideal UI for your use case? How would you like to specify that for certain scripts (like `run.jl`) you want to use a specific project path?

One thing that could work would be to use a customization variable like `eglot-jl-project-path`. With a default value of `nil`, it would tell `eglot-jl` to try and determine the project path automatically (the current behavior). A non-`nil` value would be interpreted as a project path to use instead of the default project. You could then set this as a [per-file](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) or [per-directory](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) local variable. What do you think?

@non-Jedi Any thought on this?

**Comment by johannesnauta** [comment]
Good to know that it is currently not implemented, that increases my confidence in reading emacs-lisp files a bit (as I read the `eglot-jl.el` file). 

_On your side note_: I tend to agree with this, so for now I will probably change the workflow. I personally believe that it is sometimes OK to adopt another workflow instead of trying to enforce your own -- especially if you're in the minority.

To answer your question, your suggestion is exactly like I envisioned. Personally I'd prefer to interpret it as a per-file local variable. Otherwise, I would envision a command `M-x eglot-jl-specify-project-path` that you can give the project path when a file is opened. But this is weird as you have to reload/reconfigure `eglot` after its initial load. Thus doing this on a per-file basis would probably be better.

**Comment by johannesnauta** [comment]
> As a side note, I personally never run into such an issue because I tend to put scripts (like run.jl) in the top-level directory of the package under development (i.e. alongside its Project.toml file). It's always possible to also symlink the script somewhere else if needed. But maybe this would not fit your workflow...

Just an update on this... even if I adopt your workflow (e.g. put `run.jl` in the same directory as the main `Project.toml`), I still get missing references to the package that is defined in the `Project.toml` file. Is this supposed to happen? I have a feeling that I am missing something critical -- not necessarily only related to `eglot-jl` but also closely related to packages in Julia.

**Comment by ffevotte** [comment]
> I still get missing references to the package that is defined in the `Project.toml` file. Is this supposed to happen?

I suppose not, but I often encounter the same issue when developing a script (as opposed to editing the sources of the package itself). I'm not sure how to fix this, though. (And I'm not sure it's related to `eglot-jl`)

**Comment by johannesnauta** [comment]
No worries. And I have indeed adopted that specific workaround into my workflow.
