### ISSUE TITLE
Missing references with macros

### ISSUE THREAD

**Issue by johannesnauta** [non-Jedi/eglot-jl#41]
I am unsure if this is the right repository to post this question/issue, but I am experiencing missing references when using `eglot-jl`, mostly when using macros (e.g. the `Symbolics.jl` macro `@variables`). Other than having `flymake` suppress missing references, is there perhaps a patch that fixes this? Or do you have any idea where the error might originate from?

![image](https://github.com/non-Jedi/eglot-jl/assets/26090403/7c697c20-39bf-405c-a31d-19a074fa38e9)

**Comment by ffevotte** [comment]
Yes, I think this has to do with `LanguageServer.jl`. AFAIK the issue is that `@variables` introduces a new binding `t`, which is something that you (as a human) know thanks to the semantics of the macro, but the language server does not.
In other words, consider that:
```julia
@show x      # missing reference
@variables y # this is actually fine
```
AFAIU the Language Server does not (yet?) distinguish between these two very similar constructs.

See also e.g. julia-vscode/LanguageServer.jl#1161

**Comment by johannesnauta** [comment]
Yeah that makes sense, I will close this issue here as it appears to not be an issue with `eglot-jl` specifically. I understand that it might be difficult to parse, but macros are widely used in `Julia`. For now I will just suppress the warnings until a patch appears, or until I find time to look into it more myself.
